baseURL: "https://timeline4change.com"
theme: "up-business-theme"
languageCode: "en-us"

title: "T4C"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Timeline 4 Change"
  description: "Votre partenaire préférentiel pour un futur connecté, sécurisé et en conformité"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
  #  dribbble: "#"
    instagram: "https://instagram.com/timeline4c?igshid=NGVhN2U2NjQ0Yg=="
  #  facebook: "#"
  #  twitter: "#"

  location:
    - "Guyane"
    - "Paris"

  contact:
    - "contact@timeline4change.com"
    - "+594 694 243 243" 
    - "+33 7 56 88 88 97"

  copyright: "© 2023 Timeline4Change All Rights Reserved"

menus:
  main:
    - name: "Acceuil"
      url: "/#hero"
      weight: 1

    - name: "Notre équipe"
      url: "/post/equipe"
      weight: 2

  #  - name: "Services"
  #    url: "/#"
  #    weight: 3

  buttons:
    - name: "Contactez-nous"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Acceuil"
      url: "#"
      weight: 1

  #  - name: "How we work"
  #    url: "/#"
  #    weight: 2

    - name: "Notre équipe"
      url: "/blog"
      weight: 2

  #  - name: "Prix"
  #    url: "/#"
  #    weight: 3

  #  - name: "Blog"
  #    url: "/blog"
  #    weight: 4

taxonomies:
  series: "series"
  tags: "tags"
